version: '3.4'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes: 
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql

  api:
    build: .
    restart: always
    ports:
      - 80:80
    links: 
      - "db"
    
